language: ruby
rvm:
  - 2.3.3
addons:
  postgresql: 9.5
before_script:
  - 'cp config/application.travis.yml config/application.yml'
  - "psql -c 'create database libanco_test;' -U postgres"
  - 'bundle exec rails db:migrate'
script: 'bundle exec rails test'
