source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'

gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'devise'
gem 'simple_form'
gem 'bcrypt'
gem 'kaminari'
gem 'role_model'
gem 'figaro'
gem 'paper_trail'
gem 'newrelic_rpm'
gem 'validates_timeliness'
gem 'search_cop'
gem 'font-awesome-rails'
gem 'bootstrap-datepicker-rails'
gem 'whenever', require: false
gem 'sidekiq'
gem 'authority'
gem 'apartment'
gem 'wicked_pdf'

gem 'unicorn'

group :development do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-sidekiq'
  gem 'unicorn-rails'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end
