common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'libanco' %>
  password: <%= ENV['TRAVIS'] ? '' : 'libanco' %>

development:
  database: libanco_development
  <<: *common

test:
  database: libanco_test
  <<: *common

production:
  database: libanco_production
  <<: *common

sandbox:
  database: libanco_production
  <<: *common
