# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c022dd7d27a298a76700fab5f120c2965dd7db008c82fb1f72a75f2052a99f61f0d5ea5da366900a9c366ebb135256947e753d96410dfc8c7d42eab354199a32

test:
  secret_key_base: 3e5578e1453715a3e8bfd3ebd42f5ac7c9597fba609bdc4441cab1dad3131a8f18fb1d1a6ba51636c1de31878d66fa95d0383e9cffb2e3a4cb719381e0699351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
